### 异常的概念

```
Error发生的异常事件可分为两类：
	1、Error（错误）：jvm无法解决的严重问题。如：jvm系统内部错误，资源耗尽等严重错误
	2、Exception（异常）：其它因编程错误或偶然的外在因素导致的一般问题。如：空指针访问，视图读取不存在的文件，网络连接中断等。
	Exception分为两类：
		1、运行时异常：程序运行时，发生的异常。
		2、编译时异常：编程时，编译器检查出的异常。
```

### 异常体系图

![image-20220314102401723](09%20%E5%BC%82%E5%B8%B8.assets/image-20220314102401723.png)

### 五大运行时异常

```
1、NullPointerException 空指针异常
2、ArithmeticException 数学运算异常
3、ArrayIndexOutOfBoundsException数组下标越界异常
4、ClassCastException 类型转换异常
5、NumberFormatException 数字格式不正确异常
```

```java
package com.fiveRunException;

public class Main {
    public static void main(String[] args) {
        // one();
        // two();
        // three();
        // four();
        five();
    }


    public static void one(){
        // 1、 NullPointerException 空指针异常，要访问的对象为null时
        String a = null;
        System.out.println(a.length());
    }

    public static void two(){
        // 2、 ArithmeticException 数学运算异常
        int num = 2;
        int num2 = 0;
        System.out.println(num / num2);
    }

    public static void three(){
        // 3、ArrayIndexOutOfBoundsException数组下标越界异常
        int[] arr = {1,2,3};
        for (int i = 0; i < arr.length+1; i++) {
            System.out.println(arr[i]);
        }
    }

    public static void four(){
        // 4、ClassCastException 类型转换异常
        A a = new B();
        C c = (C) a;
    }

    public static void five(){
        // 5、NumberFormatException 数字格式不正确异常
        String str = "123";
        System.out.println(Integer.parseInt(str));
        String str2 = "abc";
        System.out.println(Integer.parseInt(str2));
    }
}

class A {

}

class B extends A{

}

class C extends A{

}
```

### 常见的编译异常

```
编译异常是指在编译期间，就必须要处理的异常，否则代码不能通过编译
SQLException // 操作数据库时，查询表可能发生异常
IOException // 操作文件时，发生的异常
FileNotFoundException // 当操作不存在的文件时，发生异常
ClassNotFoundException // 加载类，而该类不存在时，异常
EOFException // 操作文件，到文件末尾时，发生异常
IIIegalArguementException // 参数异常 
```

### 异常处理trycatch

```
异常处理就是当异常发生时，对异常进行处理
try{
	// 可能有异常的代码块
}catch(Exception e){
	// 对异常的处理
}finally{
	// 必须执行的代码,释放资源等
}

try{

}catch(Exception e){

}
```

### 异常处理throws

```
1、如果一个方法中可能产生某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常做处理，而由该方法的调用者负责处理。
2、在方法声明中用throws语句可以声明抛出异常的列表，也就是多个异常，throws后面的异常类型可以是方法中产生的异常类型，也可以是异常的父类。
```

```java
package com.fiveRunException.throwsException;

public class Main {
    public static void main(String[] args) {
        calculate(1,0);
    }

    // 多异常列表
    public static void calculate(int num1,int num2) throws ArithmeticException,ClassCastException{
        System.out.println(num1 / num2);
    }
}

class A{

    /*public void hhh(){
        // 直接调用抛出编译异常（编译异常必须要处理）的方法，但是没有处理，会报错
        say();
    }*/

    public void hhh(){
        try {
            say();
        }catch(Exception e){

        }
    }

    public void say() throws Exception{

    }
}

class B extends A {
    // 子类重写父类的方法，遵循异常的继承规则（它或者它的子类）
    @Override
    public void say() throws NullPointerException {

    }
}
```

### 异常处理的注意事项

```
1、如果异常发生了，则异常发生的后面的代码不会执行，直接进入catch块。
2、如果异常没有发生，则顺序执行try代码块，不会进入到catch中。
3、如果不管是否发生异常都执行某段代码（比如关闭连接，释放资源等），则可以使用finally。
4、编译异常必须要处理，用trycatch或者throws。
5、对于运行时异常，程序中如果没有处理，默认就是throws的方式处理。
6、子类重写父类的方法时，对抛出异常的规定：子类重写的方法，所抛出的异常类型要么和父类抛出的异常一致，要么为父类抛出的异常类型的子类型。
7、在throws过程中，如果有方法trytacth，就相当于处理异常，就可以不必throws。
```

### 自定义异常

```
步骤：
	1、自定义异常类名继承Exception或者RuntimeException
	2、继承Exception，属于编译异常
	3、继承RuntimeException，属于运行时异常（实际开发用的多）
```

```java
package com.customException;

public class Main {
    public static void main(String[] args) {
        check(130);
    }

    public static void check(int age){
        if(age < 0 || age > 120){
            throw new AgeException("年龄不在0到120之间");
        }
        System.out.println("年龄正确");
    }
}

class AgeException extends RuntimeException{
    public AgeException(String message) {
        super(message);
    }
}
```

![image-20220314120530070](09%20%E5%BC%82%E5%B8%B8.assets/image-20220314120530070.png)